version: '3.9'
services:
  php-fpm:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql-db
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: check24
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user
    ports:
      - "3306:3306"